### ISSUE TITLE
Is this build executor only work for nextjs?

### ISSUE THREAD

**Issue by beckboyce2** [naxodev/oss#32]
### Current Behavior

I have a worker using no particular framework. Is this executor suited to build my project? 

### Expected Behavior

having a :build step different than :next-build step

### Steps to Reproduce

No

### Nx Report

```shell
No
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by NachoVazquez** [comment]
Hey @beckboyce2 how are you doing?

The build executor, is only for NextJS, but you don't need to use it for working with Cloudflare Workers.

For Workers you have the `serve` executor to run the worker on dev, and the `deploy` executor to deploy the worker to Cloudflare.

Let me know if you need more info.
