### ISSUE TITLE
[nx-cloudflare] Getting multiple warnings when I run my project with `serve` command

### ISSUE THREAD

**Issue by mnlbox** [naxodev/oss#36]
### Current Behavior

When I run my project through the `serve` command I'm getting this warning in my terminal:
```
▲ [WARNING] kj/filesystem-disk-unix.c++:1709: warning: PWD environment variable doesn't match current directory; pwd = /mnlbox
```

### Expected Behavior

It's a bit annoying as it prints two warning each time the server reload so it's a bit noisy in the terminal.
Should I ignore it or it's a bug on the `serve` command? Or maybe my project structure is not correct? 🤔 

### Steps to Reproduce

1. Create my project with this command:
```
pnpm nx generate @naxodev/nx-cloudflare:application --name api-test--template hono --directory apis/test --port 4001 --projectNameAndRootFormat=as-provided
```

2. Then run my project with this command:
```
pnpm nx serve api-test
```

My project is run successfully and I can see the `Hello Hono!` message in the browser when I visit: http://localhost:4001
But I'm getting two warning like this:
```
 ⛅️ wrangler 3.48.0
-------------------
▲ [WARNING] kj/filesystem-disk-unix.c++:1709: warning: PWD environment variable doesn't match current directory; pwd = /mnlbox


[wrangler:inf] Ready on http://localhost:4001
⎔ Starting local server...
▲ [WARNING] kj/filesystem-disk-unix.c++:1709: warning: PWD environment variable doesn't match current directory; pwd = /mnlbox

```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.0
OS     : linux-arm64
pnpm   : 8.15.5

nx                 : 18.2.4
@nx/js             : 18.2.4
@nx/jest           : 18.2.4
@nx/linter         : 18.2.4
@nx/eslint         : 18.2.4
@nx/workspace      : 18.2.4
@nx/devkit         : 18.2.4
@nx/esbuild        : 18.0.6
@nx/eslint-plugin  : 18.2.4
@nx/nest           : 18.2.4
@nx/node           : 18.2.4
@nx/playwright     : 18.2.4
@nx/react          : 18.2.4
@nrwl/tao          : 18.2.4
@nx/vite           : 18.2.4
@nx/web            : 18.2.4
@nx/webpack        : 18.2.4
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/vite/plugin
@nx/playwright/plugin
---------------------------------------
Community plugins:
@naxodev/nx-cloudflare : 2.0.1
---------------------------------------
The following packages should match the installed version of nx
  - @nx/esbuild@18.0.6
  - @nrwl/esbuild@18.0.6

To fix this, run `nx migrate nx@18.2.4`
```

### Operating System

- [x] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I'm using vscode devContainer with a Debian based linux in a MacOs host machine.

**Comment by mnlbox** [comment]
And BTW as I checked the `NX report` now I think the `@nx/esbuild` package is installed by `@naxodev/nx-cloudflare` package to build the cloudflare function but it seems the version is not matched based on this section of `NX report`:
```
The following packages should match the installed version of nx
  - @nx/esbuild@18.0.6
  - @nrwl/esbuild@18.0.6
 ```

Maybe it's better to have these packages as as `peerDependencies` or maybe just update them in the generator.

**Comment by NachoVazquez** [comment]
Hey @mnlbox, thanks for the thorough issue! 

Regarding the warning, this is very likely coming from Wrangler. You can verify that by running `wrangler dev` directly on the application folder. This `serve` executor wraps over it.

Regarding the version mismatch, that's a good catch, so I'll have it fixed.

**Comment by mnlbox** [comment]
And BTW, one more small suggestion: I guess it's useful to add the [project website url](https://github.com/naxodev/oss/tree/main/packages/nx-cloudflare) to the NPM page here as well:
https://www.npmjs.com/package/@naxodev/nx-cloudflare

I had to search and find this repo from your GitHub profile to report this issue as there was no website available on the NPM page of the **nx-cloudflare** package. 

And thanks for this awesome and useful project. I like it ❤️ 
It's a good idea to organize all of the tiny Cloudflare Worker projects in an NX monorepo. 😉

**Comment by NachoVazquez** [comment]
I was able to reproduce your issue; it should be easier to address now.

**Comment by NachoVazquez** [comment]
I know what the problem is. We need to set the `cwd` on the forked thread to aim for the project folder, but that's not changing the matching of the `pwd`, which is the project's root.

**Comment by mnlbox** [comment]
@NachoVazquez Thanks for your support. I'll fix it whenever you release it and update you here 😉

**Comment by NachoVazquez** [comment]
I'll release this changes with the fixes to the `deploy/publish` command
